// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title IGroth16Verifier
/// @notice Minimal interface for Groth16 verifiers generated by `snarkjs`.
interface IGroth16Verifier {
    /// @notice Verify a Groth16 proof produced off-chain.
    /// @dev The concrete implementation is circuit-specific and generated from `.zkey` files.
    /// @param a First proof element.
    /// @param b Second proof element.
    /// @param c Third proof element.
    /// @param publicSignals Flattened array of public inputs for the circuit.
    /// @return valid True when the proof satisfies the verification key constraints.
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[] calldata publicSignals
    ) external returns (bool valid);
}
